site_name: PesquisaUnB

nav:
  - Início: "index.md"
  - Atas de Reunião:
    - Ata 1: "atas-reuniao/ata-reuniao-1.md"
    - Ata 2: "atas-reuniao/ata-reuniao-2.md"
    - Ata 3: "atas-reuniao/ata-reuniao-3.md"
    - Ata 4: "atas-reuniao/ata-reuniao-4.md"
  - Documentos:
    - Visão do produto: "documentos/Produto.md"

theme:
  name: material

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
